# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/pluck_to_hash/all/pluck_to_hash.rbi
#
# pluck_to_hash-1.0.2

module PluckToHash
  extend ActiveSupport::Concern
end
module PluckToHash::ClassMethods
  def format_keys(keys); end
  def get_correct_hash_type(hash, hash_type); end
  def pluck_h(*keys); end
  def pluck_s(*keys); end
  def pluck_to_hash(*keys); end
  def pluck_to_struct(*keys); end
end
class ActiveRecord::Base
  extend PluckToHash::ClassMethods
  include PluckToHash
end
